import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import { sassPlugin } from 'esbuild-sass-plugin'
import svgrPlugin from 'esbuild-plugin-svgr';

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    minify: prod,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins],
    format: 'cjs',
    watch: !prod,
    target: 'es2016',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    plugins: [svgrPlugin()]
}).catch(() => process.exit(1));

esbuild.build({
    entryPoints: ['styles.scss'],
    outfile: "styles.css",
    bundle: true,
    watch: !prod,
    external: ['*.eot','*.eot#iefix'],
    plugins: [sassPlugin({
        cssImports: true,

        type: "css"
    }),
    {
        name: "temp", setup(build) {
            build.onResolve({ filter: /^~.*css$/ }, ({ path }) => {
                return { path: require.resolve(path.slice(1)) }
            })
        }
    }

    ],
    loader: {
        ".woff": "dataurl",
        ".woff2": "dataurl",
        ".ttf": "dataurl",
        ".png": "dataurl"
      }
}).catch(() => process.exit(1));
